---

- name: Red Hat Subscription
  import_role:
    name: redhat_subscription
  tags:
    - redhat_subscription

- name: Install packages
  yum:
    name: 
      - openstack-packstack
      - python-setuptools
      - yum-utils
    state: present

- name: Make sure a service is running
  systemd:
    enabled: no
    state: stopped
    name: "{{ item }}"
  with_items:
    - firewalld
    - NetworkManager
  
- name: Update all packages
  yum:
    name: "*"
    state: latest

- name: Update grub config
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX='
    line: 'GRUB_CMDLINE_LINUX="biosdevname=0 crashkernel=auto nomodeset rd.auto=1 consoleblank=0 intel_iommu=on"'
    backup: yes
  register: updategrub

- name: Update grub
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: updategrub.changed == True

- name: Reboot ....
  reboot:
    reboot_timeout: 3600
  when: updategrub.changed == True


- name: Packstage gen answer file
  command: packstack --gen-answer-file /root/answers.txt
  args:
    creates: /root/answers.txt

- name: Update answers.txt
  lineinfile:
    path: /root/answers.txt
    regexp: "^{{ item.name }}"
    line: "{{ item.name }}={{ item.value}}"
  with_items:
    - { name: "CONFIG_NTP_SERVERS", value: "0.pool.ntp.org,1.pool.ntp.org,2.pool.ntp.org" }
    - { name: "CONFIG_KEYSTONE_ADMIN_PW", value: "redhat" }
    - { name: "CONFIG_PROVISION_DEMO", value: "n" }
    - { name: "CONFIG_HEAT_INSTALL", value: "y" }
    - { name: "CONFIG_HEAT_CFN_INSTALL", value: "y" }
    - { name: "CONFIG_CEILOMETER_INSTALL", value: "y" }
    - { name: "CONFIG_LBAAS_INSTALL", value: "y" }
    - { name: "CONFIG_CINDER_VOLUMES_CREATE", value: "n" }
    - { name: "CONFIG_NOVA_SCHED_RAM_ALLOC_RATIO", value: "3.0" }
    - { name: "CONFIG_NOVA_LIBVIRT_VIRT_TYPE", value: "kvm" }
    - { name: "CONFIG_HORIZON_SSL", value: "y" }

- name: Run packstage, take some time
  command: packstack --answer-file /root/answers.txt --timeout=1500